export default {
  moshuUpstream: {
    title: 'Upstream',
    protocolDisabled: 'Reseller protocol is not enabled',
    protocolDisabledHint: 'Manual per-group keys remain available. Enable MOSHU_RESELLER_CLIENT_ENABLED to use enrollment.',
    enrollTitle: 'Connect to Moshu reseller',
    enrollHint: 'Enter a one-time enrollment code generated by Moshu. It expires immediately after exchange.',
    baseUrl: 'Moshu base URL',
    enrollmentCode: 'One-time enrollment code',
    connect: 'Connect and load products',
    connected: 'Moshu reseller connection established',
    syncCatalog: 'Sync upstream settings',
    catalogSynced: 'Upstream settings synchronized',
    authorizedProducts: 'Authorized products',
    revoked: 'Revoked',
    salesName: 'Retail group name',
    enableSale: 'Create retail group',
    rotate: 'Rotate credential',
    rotated: 'Product credential rotated',
    saleActive: 'Sales enabled',
    stopSale: 'Stop selling',
    productSaved: 'Retail product configuration saved',
    productStopped: 'Product sale stopped',
    costMultiplier: 'Cost multiplier',
    allModels: 'All models',
    modelCount: '{count} models',
    retailMultiplier: 'Retail multiplier',
    loadFailed: 'Failed to load upstream details',
    status: {
      active: 'Active',
      inactive: 'Inactive',
      error: 'Error'
    }
  }
}
